version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: hr-automation-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: hr_automation
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
